language: node_js
node_js:
  - "stable"
addons:
  chrome: stable
cache:
  directories:
  - node_modules
before_install:
  - npm install -g @lhci/cli@0.3.x
script:
  - npm test
  - npm run build
  - lhci autorun # run lighthouse CI